/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Skill = IDL.Record({ 'name' : IDL.Text, 'level' : IDL.Nat });
export const Project = IDL.Record({
  'skillsUsed' : IDL.Vec(Skill),
  'link' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Portfolio = IDL.Record({
  'bio' : IDL.Text,
  'projects' : IDL.Vec(Project),
  'skills' : IDL.Vec(Skill),
});

export const idlService = IDL.Service({
  'addProject' : IDL.Func([IDL.Text, Project], [], []),
  'addSkill' : IDL.Func([IDL.Text, Skill], [], []),
  'createPortfolio' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(Skill), IDL.Vec(Project)],
      [],
      [],
    ),
  'getPortfolio' : IDL.Func([IDL.Text], [Portfolio], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Skill = IDL.Record({ 'name' : IDL.Text, 'level' : IDL.Nat });
  const Project = IDL.Record({
    'skillsUsed' : IDL.Vec(Skill),
    'link' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Portfolio = IDL.Record({
    'bio' : IDL.Text,
    'projects' : IDL.Vec(Project),
    'skills' : IDL.Vec(Skill),
  });
  
  return IDL.Service({
    'addProject' : IDL.Func([IDL.Text, Project], [], []),
    'addSkill' : IDL.Func([IDL.Text, Skill], [], []),
    'createPortfolio' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(Skill), IDL.Vec(Project)],
        [],
        [],
      ),
    'getPortfolio' : IDL.Func([IDL.Text], [Portfolio], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };