/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Portfolio {
  'bio' : string,
  'projects' : Array<Project>,
  'skills' : Array<Skill>,
}
export interface Project {
  'skillsUsed' : Array<Skill>,
  'link' : string,
  'name' : string,
  'description' : string,
}
export interface Skill { 'name' : string, 'level' : bigint }
export interface _SERVICE {
  'addProject' : ActorMethod<[string, Project], undefined>,
  'addSkill' : ActorMethod<[string, Skill], undefined>,
  'createPortfolio' : ActorMethod<
    [string, string, Array<Skill>, Array<Project>],
    undefined
  >,
  'getPortfolio' : ActorMethod<[string], Portfolio>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];